config/routes.rb
Rails.application.routes.draw do
  
  resources :favorites
  resources :profiles

  resources :posts do
    resources :comments
  end

  devise_for :users, controllers: { sessions: "users/sessions" }
  root 'posts#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  #belongs_to :user, :optional => true
  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :desciption, :image, presence: true
  belongs_to :user 
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:desciption, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, url: posts_path, html: { multipart: true } do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :desciption %>
    <%= form.text_area :desciption %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 >Lists Posts</h1>

<br><br>
<table>
  <thead>
   <h2> Posts from your friends! you can view details</h2>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
      <%= post.user.email %><br>
        <%= image_tag post.image.url %><br>
        <p ><%= post.desciption %></p><br>
        
        
        <%= link_to 'Details', post, class: "btn btn-info" %>
        <% if post.user == current_user %>
        <%= link_to 'Edit ', edit_post_path(post), class: "btn btn-warning" %>
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>
<div class = "row">
<div >

<br>

<%= link_to 'Create New Post', new_post_path, class: "btn btn-success" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.desciption %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url %>
</p>
<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Cancel favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Make it a favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<p>List of Comments(Contents below are important)</p>

  <!-- Get an HTML id of this comments_area and update only the part of that div -->
  <div id="comments_area">
    <!-- Render to display the posted comment list on the blogs detail page -->
    <%= render partial: 'comments/index', locals: { comments: @comments, post: @post } %>
  </div>

  <!-- Render to display the comment field on the blogs detail page -->
  <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-warning' %>